name: Write Result to Branch

on: [push]
  # push:
  #   branches:
  #     - main  # Trigger the workflow on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2  # Checkout the repository

    - name: Run Task and Save Result
      run: |
        # Your task or script to generate the result
        echo "Result of the task" > result.txt

    - name: Commit Result to Branch
      run: |
        git config --global user.email "youngsu.kim@csusb.edu"
        git config --global user.name "youngsuKim-CSUSB"
        git add result.txt
        git commit -m "Update result.txt with latest task result"
        
    - name: Push Changes to Branch
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main  # Branch where you want to push the changes
