name: Write Result to Branch
run-name: S2024 dawg demo
on: [push]
  # push:
  #   branches:
  #     - main  # Trigger the workflow on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     python-version: ["pypy3.9", "pypy3.10", "3.9", "3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    # - name: Install R
    #   uses: r-lib/actions/setup-r@v2
    - name: Run Task and Save Result
      run: |
        # git checkout output
        git pull  
        python -c "import sys; print(sys.version)" >> python_version.txt
        echo $(R --version) >> r_version.txt
        echo $(date +"Today's date is %A, %B %d, %Y") >> output.txt
        cd python_files
        for file in $(ls); do echo $file >> ../python_output.txt; done      
        cd ..
        #
        cd r_files
        for file in $(ls); do echo $file >> ../r_output.txt; done      
        cd ..
        #
        cd text_files
        for file in $(ls); do echo $file >> ../text_output.txt; done      
        cd ..

    - name: Commit Changes to Branch
      run: |
        git config --global user.email "youngsu.kim@csusb.edu"
        git config --global user.name "youngsuKim-CSUSB"
        ls -all
        git add python_version.txt r_version.txt python_output.txt r_output.txt text_output.txt
        git status
        git commit -m "dawg demo edit files"
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: output
        force: true
